CREATE TABLE user.tbl_users (
    username VARCHAR(20) PRIMARY KEY NOT NULL UNIQUE,
    uid VARCHAR(100) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone_no VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    selected_locale VARCHAR(2) NOT NULL,
    user_active BOOLEAN NOT NULL DEFAULT TRUE,
    stripe_customer_id VARCHAR(100),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
